Simplify the description of functions.
face-hh/bussin pull request #59
Opened 2024-04-13 22:18 UTC by cablesalty

Just simplified the description of "functions". No need to thank me.

I definitely did not use any popular language augmentation tool resembling an intricate neural network, adept at understanding human language intricacies.

2024-04-13 22:21 UTC, Symmettry commented
I think it's too simple, you might wanna add a bit more.

2024-04-13 22:23 UTC, cablesalty commented
@Symmettry Apologies for the oversimplifications.

2024-07-07 16:24 UTC, pendragons-code commented
One day, someone might just very well make an actual project using this 😢

2024-07-23 00:16 UTC, hueychen27 requested changes
Too short. This does not match with Bussin X's style.

2025-01-19 13:23 UTC, closed without merging